src/components/LocaleSwitcher.vue
src/components/PageShallow.vue
src/components/UiButton.vue
src/components/UiSelect.vue
src/components/UiTextField.vue
src/components/UserProfileCompany.vue
src/components/UserProfilePerson.vue
src/locales/scheme.js
src/pages/UserProfile.vue

Сам свитчер
Ещё добавил звёздочки-реквайрюшки, потому что погода в стане менеджеров поменялось и теперь они нужны )

Locale switcher

---

src/components/LayoutHeader.vue

Добавил v-clickaway для попапов, поменял некоторые текста, избавился от универсальности инфы для статусов

Small fixes

---

src/components/Layout.vue
src/components/LayoutHeader.vue
src/components/LayoutSubHeader.vue
src/components/UiProgressRing.vue

Add LayoutSubHeader

---

src/components/Layout.vue
src/components/Page.vue
src/components/PageNoLayout.vue
src/components/PageShallow.vue
src/components/StepsProgressBar.vue
src/components/UiButton.vue
src/components/UiSelect.vue

Список правок тут https://protocol1.atlassian.net/browse/PAY-406
Помимо них убрал пересечение стилей для html/body, которое прилетало от layout-ов (снова я продолбался :D )

Profile fixes

---

src/components/LocaleSwitcher.vue
src/components/UiSelect.vue
src/components/UiTextField.vue
yarn.lock

По ещё двум замечаниям от Саши Русака:
1. Иконка dropdown не переворачивается в инпуте при его фокусе и не меняет цвет.
2. В менюшке выбора языков старое наведение.

some view fixes for user profile

---

src/errors.js
src/store/MerchantStore.js
src/store/UserStore.js

Небольшой фикс авторизации.
Теперь она не будет слетать после рефреша + фикс вывода ошибок

auth mechanism change

---

src/components/AccountInfo.vue
src/components/BankingInfo.vue
src/components/Contacts.vue
src/components/SmartListItem.vue
src/components/UiSelect.vue
src/pages/Company.vue

Add BankingInfo component and style fixes

---

src/components/LayoutHeader.vue
src/components/LicenseAgreement.vue
src/components/Notifications.vue
src/routes.js
yarn.lock

Add Notifications block

---

package.json
src/components/LayoutHeader.vue
src/components/LeaveFeedbackPopup.vue
src/components/UiButton.vue
src/components/UiScrollbarBox.vue
src/components/UiTip.vue
src/store/LeaveFeedbackStore.js
src/store/RootStore.js
yarn.lock

leaving feedback for a page popup

---

src/components/ErrorPage.vue
src/pages/TaxesCardCountryPage.vue
src/pages/TaxesCardPage.vue
src/pages/TaxesCardPeriodPage.vue
src/pages/TaxesListPage.vue
src/plugins/misc.js
src/routes.js
src/schemes/taxesByCountryScheme.js
src/schemes/taxesByPeriod.js
src/schemes/taxesListScheme.js
src/store/RootStore.js
src/store/TaxesByCountryStore.js
src/store/TaxesByPeriodStore.js
src/store/TaxesListStore.js

adds taxes pages

---

.eslintrc.js
src/components/AccountInfo.vue
src/components/AgreementProgressWidget.vue
src/components/BankingInfo.vue
src/components/Contacts.vue
src/components/LayoutSpecialNavProgress.vue
src/components/SmartListItem.vue
src/components/UiProgressRing.vue
src/pages/Company.vue
src/pages/Dashboard.vue
src/store/AccountInfoStore.js
src/store/BankingInfoStore.js
src/store/CompanyStore.js
src/store/ContactsStore.js
src/store/LicenseAgreementStore.js
src/store/MerchantStore.js
src/store/UserStore.js

Решил вылить правки критических багов, которые не позволяли просто тестировать и даже заходить под новым пользователем в онбординг.
Плюс там же часть логики по отображению шагов и их статусов и часть других багов и правок захватил. Не стал дополнительные коммиты делать разбивая критическое и не критическое, чтобы время не терять, всё равно это всё выливать

Ui onboarding bugs

---

src/pages/ComponentsPage.vue
src/routes.js

Shared ui components listing page

---

src/components/FileDownload.vue
src/components/OrderSearchPanel.vue
src/main.js
src/pages/TransactionCard.vue
src/pages/revenue.vue
src/plugins/extendAxios.js
src/store/AccountInfoStore.js
src/store/BankingInfoStore.js
src/store/ContactsStore.js
src/store/DashboardStore.js
src/store/LeaveFeedbackStore.js
src/store/LicenseAgreementStore.js
src/store/MerchanstListStore.js
src/store/MerchantHistoryStore.js
src/store/MerchantPaymentMethodStore.js
src/store/MerchantStore.js
src/store/PayoutStore.js
src/store/ProductStore.js
src/store/ProjectGameKeysStore.js
src/store/ProjectStore.js
src/store/ProjectsListStore.js
src/store/RootStore.js
src/store/TariffStore.js
src/store/TaxesByCountryStore.js
src/store/TaxesByPeriodStore.js
src/store/TaxesListStore.js
src/store/TransactionsSearchStore.js
src/store/UserProfileStore.js

Магия здесь
https://github.com/paysuper/paysuper-management-server/pull/82/files#diff-ba34e55ff03aa328d27ae8d4d8c2cdaa

global extending axios with accessToken + removing it in local use cases

---

src/pages/ProjectPage.vue
src/pages/ProjectSettingsPage.vue
src/store/ProjectStore.js

Для получения более удобного формата
```
[
{"region":"USD","currency":"USD"},
{"region":"NAFRICA","currency":"USD"}
]
```

#191948 currenciesDetailed getter at Project store

---

package.json
src/components/UiLangTextField.vue
src/components/UiTextField.vue
yarn.lock

Сделал новый режим для UiTextField - isNumeric
Раньше уже был реализован режим isMoney, но посмотрите в чём проблема:
Если резюмировать:
1. Конченый процесс ввода (сперва вводятся десятичные, потом переходит на основные цифры)
2. Количество цифр после запятой по сути фиксировано
3. Невозможность оставить инпут и связанное значение пустым

UiTextField new option - numeric

---

src/plugins/extendAxios.js
src/store/UserStore.js

По заявке Алекса )
Теперь авторизация будет протухань намного дольше (будет держаться аж 3,5 дня) благодаря авто-рефрешу токена на запросах, которые обосрались с 401 (главное, не забыть при авторизации тыкнуть галочку `offline`)

auth token auto-refresh

---

public/index.html

Базовый прелодер, пока приложение скачивается и инициализируется

preloader for state where app is not inited yet

---

.helm/values.yaml
backend/app/middleware/order-page.js
backend/app/middleware/router.js
backend/templates/order-page.hbs
package.json
src/pages/PaymentFormSdk.vue
yarn.lock

Новая страница платёжной формы. 
Первое приближение (пока без обработки входящих параметров order и token. ещё жду правок бекенда)
Отдаётся статикой с бекенда, чтобы не грузилось приложение.
Будет доступно по урлам
https://paysupermgmt.tst.protocol.one/order
http://localhost:8080/order

#192163 static payment form page. first version

---

src/components/UiSelect.vue
src/pages/UserProfilePage.vue
src/pages/index.vue
src/router.js
src/routes.js
src/store/UserProfileStore.js
src/store/UserStore.js

- Пользователь после регистрации попадает на заполнение профиля
- Если страница требует авторизации, а email не подтверждён -> редирект на заполнение профиля
- Если email подверждён попытка зайти в профиль выкидывает в /dashboard

#192395 disabling dashboard access until user profile is complete

---

src/components/Layout.vue
src/components/LayoutMainNavDefault.vue
src/components/NewProjectModal.vue
src/helpers/getMerchantMainNavItems.js
src/pages/ProjectPage.vue
src/pages/ProjectsListPage.vue
src/routes.js
src/store/ProjectStore.js
src/store/ProjectsListStore.js

1. Сделал меню проектов недоступным, если не создан мёрчант (не начато заполнение анкеты для подписания), ибо для проектов нужен merchant_id
2. Доделал быстрое создание проекта (сразу же из модалки создания по двум параметрам: name и image)

makes projects list unavailable if no merchant + fast project creation

---

src/components/PaymentMethods.vue

changes for payment methods in company page, #192372

---

src/components/LayoutSpecialNavProgress.vue
src/pages/PaymentFormSdk.vue

Вот добавленные для ключей
И три продукта:

Fix ProgressRing, fix data for form-demo

---

src/components/AccountInfo.vue
src/components/IconTwoArrowsToInside.vue
src/components/LayoutMainNavProject.vue
src/components/UiTextField.vue
src/components/UserProfileCompany.vue
src/pages/ProjectPaymentFormPage.vue
src/pages/ProjectWebhooksPage.vue
src/routes.js

#192510 adds Payment form settings page into Project pages group +autocompleteUrlProtocol option for UiTextField

---

src/components/UiTextField.vue

#192442 fix UiTextInput suggest toggling process

---

src/components/UiButton.vue
src/pages/ProjectKeyProductsListPage.vue
src/pages/ProjectVirtualItemsPage.vue

fixing UiButton transprent disabled style

---

src/pages/UserInviteProfilePage.vue
src/pages/UserProfilePage.vue
src/routes.js

Верстка страницы авторизации и регистрации заинвайченного пользователя.
Без интеграции с реальным процессом регистрации (хотя если @Temarie знает как это должно работать, можно заинтегироватья)

#192397 user invite profile page

---

src/components/PaymentMethods.vue
src/components/UiSelect.vue
src/helpers/formatNumber.js
src/store/TariffStore.js

Fix formats for amounts in PaymentMethods component

---

src/components/AccountInfo.vue
src/components/UiAutocomplete.vue
src/store/DictionariesStore.js

Account info | Country autocomplete

---

package-lock.json
package.json
src/components/UiSelect.vue
src/main.js
src/plugins/inView.js

UiSelect теперь дропается вверх если находится близко к нижнему краю экрана

fix UiSelect

---

src/components/LayoutHeader.vue
src/main.js
src/pages/index.vue
src/plugins/extendAxios.js

Досвидосим из админки, если токен совсем протух

#192842 throw out of admin if token is expired and can't be refreshed

---

src/pages/payoutCard.vue
src/store/PayoutCardStore.js

Royalty reports for payout card

---

src/components/ProjectEntityPricesForm.vue

Сейчас отваливается запрос на бекенде и задетектил неправильную обработку ошибки.
В текущем состоянии у нас не выключается глобальный прелодер

handling getRecommendedPrices error inside ProjectEntityPricesForm properly

---

src/pages/ProjectKeyProductPage.vue
src/pages/ProjectSettingsPage.vue
src/pages/ProjectVirtualCurrencyPage.vue
src/pages/ProjectVirtualItemEditPage.vue
src/plugins/vuelidate.js

Поправил валидацию полей UiLangTextField

Validation

---

src/components/MerchantAdminChannelCostsTable.vue
src/components/MerchantAdminChargebackTable.vue
src/components/MerchantAdminFormPaymentMethods.vue
src/components/MerchantAdminRefundCostsTable.vue
src/components/UiTextFieldReadonly.vue
src/mixins/PaymentMethodsTable.js
src/pages/MerchantAdminCompanyInfoPage.vue
src/pages/MerchantAdminPaymentMethodsPage.vue
src/store/MerchantTariffStore.js

Добавляем возможность админу править тарифы мерчанта, правим несколько небольших багов

Fix onboarding bugs 7

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support-request.md
CONTRIBUTING.md
README.md

new contributing.md
new issue templates
readme update to include contributing

contributing, issue templates, readme update

---

src/store/AccountInfoStore.js

Пробрасывать данные из первичного онбординга в данные мерчанта в Company info:
Company name -> Operating name
Website -> Website

192884 pass some primary onboarding fields into secondary one

---

src/components/UiLabelTag.vue
src/pages/TransactionCardPage.vue

193525 adds Test tag into Transaction Page
